# backend/services/domain/intelligence/user_snapshot_service.py

"""
User Context Snapshot Service for MindPal.

Synthesizes a natural-language "current understanding" snapshot of where the user is
(dominant themes, tone trajectory, active stressors, what's been helping lately).
Regenerated by AI when meaningful signal changes are detected (e.g. shift in mood, new themes, or memory updates).
Injected into chat orchestration to adapt MindPal's support to the user's present reality.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from backend.core.config import Settings
from backend.core.security import sanitize_text
from backend.models.understanding import MessageUnderstanding, UserContextSnapshot
from backend.services.domain.llm.request_builder import build_llm_request
from backend.services.domain.llm.service import LLMService

logger = logging.getLogger(__name__)

SNAPSHOT_SYNTHESIS_SYSTEM_PROMPT = """You are MindPal's user-context synthesis AI.
Given recent message understanding records and memory context, synthesize a dynamic situational snapshot of the user's present reality.

Return JSON ONLY matching this exact structure:
{
  "dominant_themes": ["theme1", "theme2"],
  "tone_trajectory": "concise description of how user's mood/tone has evolved recently",
  "active_stressors": ["stressor1", "stressor2"],
  "what_helps": ["effective_coping_1", "effective_coping_2"],
  "situational_portrait": "a gentle, natural-language synthesis of where the user currently stands emotionally and situationally"
}

Rules:
- Focus on present situation, recent trajectory, active stressors, and what helps.
- Do not repeat full raw message transcripts.
- Keep output empathetic, concise, and privacy-focused.
""".strip()


class UserSnapshotService:
    """Service to maintain and re-synthesize dynamic user-context snapshots."""

    def __init__(
        self,
        *,
        settings: Settings,
        llm_service: LLMService | None = None,
    ) -> None:
        self.settings = settings
        self.llm_service = llm_service
        self._snapshots: dict[str, UserContextSnapshot] = {}  # key: user_id_hash

    def get_snapshot(self, user_id_hash: str) -> UserContextSnapshot | None:
        clean_hash = sanitize_text(user_id_hash or "", 120)
        return self._snapshots.get(clean_hash)

    def should_regenerate(
        self,
        user_id_hash: str,
        recent_understandings: list[MessageUnderstanding],
    ) -> bool:
        """
        Detect if signal has changed meaningfully (not on a dumb timer).
        Triggers if:
        1. No snapshot exists yet and there are understandings.
        2. High crisis/distress signal appears in latest understanding.
        3. High memory-worthiness (>0.7) item encountered.
        4. New themes or emotional shifts detected in latest message.
        """
        clean_hash = sanitize_text(user_id_hash or "", 120)
        snapshot = self._snapshots.get(clean_hash)
        if not snapshot:
            return bool(recent_understandings)

        if not recent_understandings:
            return False

        latest = recent_understandings[-1]

        # Trigger on high memory worthiness
        if latest.memory_worthiness >= 0.7:
            return True

        # Trigger on elevated crisis risk assessment
        if latest.crisis_risk_assessment in {"medium", "high"}:
            return True

        # Trigger on new dominant themes not in snapshot
        snapshot_themes = set(snapshot.dominant_themes)
        new_themes = set(latest.themes)
        if new_themes and not new_themes.issubset(snapshot_themes):
            return True

        return False

    async def regenerate_snapshot(
        self,
        user_id_hash: str,
        understandings: list[MessageUnderstanding],
        memory_summary_text: str = "",
        trigger_reason: str = "signal_change",
        request_id: str = "snapshot-regen",
    ) -> UserContextSnapshot:
        """Regenerate the user-context snapshot using LLM synthesis."""
        clean_hash = sanitize_text(user_id_hash or "", 120)
        existing = self._snapshots.get(clean_hash)
        new_version = (existing.version + 1) if existing else 1

        if not self.llm_service or not understandings:
            fallback = UserContextSnapshot(
                user_id_hash=clean_hash,
                version=new_version,
                dominant_themes=[t for u in understandings for t in u.themes][:5],
                tone_trajectory=understandings[-1].emotional_state if understandings else "neutral",
                active_stressors=[],
                what_helps=[],
                situational_portrait="Initial situational snapshot.",
                trigger_reason=trigger_reason,
            )
            self._snapshots[clean_hash] = fallback
            return fallback

        input_payload = {
            "recent_understandings": [
                {
                    "emotional_state": u.emotional_state,
                    "themes": u.themes,
                    "significance": u.significance,
                    "memory_worthiness": u.memory_worthiness,
                    "crisis_risk": u.crisis_risk_assessment,
                }
                for u in understandings[-10:]
            ],
            "memory_context": sanitize_text(memory_summary_text or "", 1000),
        }

        try:
            req = build_llm_request(
                request_id=f"{request_id}:snapshot-regen",
                system_prompt=SNAPSHOT_SYNTHESIS_SYSTEM_PROMPT,
                user_message=json.dumps(input_payload, ensure_ascii=False),
                temperature=0.2,
                max_output_tokens=600,
                metadata={"purpose": "user_context_snapshot_synthesis"},
            )
            res = await self.llm_service.generate_with_trace(req)
            parsed = self._parse_snapshot_output(
                raw_text=res.response.text,
                user_id_hash=clean_hash,
                version=new_version,
                trigger_reason=trigger_reason,
            )
            self._snapshots[clean_hash] = parsed
            return parsed
        except Exception as exc:
            logger.warning("Snapshot regeneration failed for %s: %s", clean_hash, exc)
            fallback = UserContextSnapshot(
                user_id_hash=clean_hash,
                version=new_version,
                dominant_themes=[t for u in understandings for t in u.themes][:5],
                tone_trajectory=understandings[-1].emotional_state if understandings else "neutral",
                active_stressors=[],
                what_helps=[],
                situational_portrait="Situational snapshot synthesis unavailable.",
                trigger_reason=trigger_reason,
            )
            self._snapshots[clean_hash] = fallback
            return fallback

    def delete_snapshot_for_user(self, user_id_hash: str) -> bool:
        clean_hash = sanitize_text(user_id_hash or "", 120)
        if clean_hash in self._snapshots:
            del self._snapshots[clean_hash]
            return True
        return False

    def _parse_snapshot_output(
        self,
        raw_text: str,
        user_id_hash: str,
        version: int,
        trigger_reason: str,
    ) -> UserContextSnapshot:
        cleaned = raw_text.strip()
        if cleaned.startswith("```"):
            lines = cleaned.splitlines()
            cleaned = "\n".join(lines[1:-1]).strip() if len(lines) > 2 else ""

        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start >= 0 and end > start:
            cleaned = cleaned[start : end + 1]

        data = json.loads(cleaned)
        if not isinstance(data, dict):
            raise ValueError("Output must be a JSON object")

        return UserContextSnapshot(
            user_id_hash=user_id_hash,
            version=version,
            dominant_themes=list(data.get("dominant_themes") or []),
            tone_trajectory=str(data.get("tone_trajectory") or ""),
            active_stressors=list(data.get("active_stressors") or []),
            what_helps=list(data.get("what_helps") or []),
            situational_portrait=str(data.get("situational_portrait") or ""),
            trigger_reason=trigger_reason,
        )
