// frontend/js/voice_languages.js

export const VOICE_LANGUAGE_OPTIONS = [
  { value: "auto", label: "Auto / Browser default", nativeLabel: "Auto" },

  { value: "af-ZA", label: "Afrikaans — South Africa", nativeLabel: "Afrikaans" },
  { value: "sq-AL", label: "Albanian — Albania", nativeLabel: "Shqip" },
  { value: "am-ET", label: "Amharic — Ethiopia", nativeLabel: "አማርኛ" },

  { value: "ar-DZ", label: "Arabic — Algeria", nativeLabel: "العربية — الجزائر" },
  { value: "ar-BH", label: "Arabic — Bahrain", nativeLabel: "العربية — البحرين" },
  { value: "ar-EG", label: "Arabic — Egypt", nativeLabel: "العربية — مصر" },
  { value: "ar-IQ", label: "Arabic — Iraq", nativeLabel: "العربية — العراق" },
  { value: "ar-JO", label: "Arabic — Jordan", nativeLabel: "العربية — الأردن" },
  { value: "ar-KW", label: "Arabic — Kuwait", nativeLabel: "العربية — الكويت" },
  { value: "ar-LB", label: "Arabic — Lebanon", nativeLabel: "العربية — لبنان" },
  { value: "ar-MA", label: "Arabic — Morocco", nativeLabel: "العربية — المغرب" },
  { value: "ar-OM", label: "Arabic — Oman", nativeLabel: "العربية — عُمان" },
  { value: "ar-QA", label: "Arabic — Qatar", nativeLabel: "العربية — قطر" },
  { value: "ar-SA", label: "Arabic — Saudi Arabia", nativeLabel: "العربية — السعودية" },
  { value: "ar-TN", label: "Arabic — Tunisia", nativeLabel: "العربية — تونس" },
  { value: "ar-AE", label: "Arabic — UAE", nativeLabel: "العربية — الإمارات" },
  { value: "ar-YE", label: "Arabic — Yemen", nativeLabel: "العربية — اليمن" },

  { value: "hy-AM", label: "Armenian — Armenia", nativeLabel: "Հայերեն" },
  { value: "az-AZ", label: "Azerbaijani — Azerbaijan", nativeLabel: "Azərbaycanca" },
  { value: "eu-ES", label: "Basque — Spain", nativeLabel: "Euskara" },
  { value: "bn-BD", label: "Bengali — Bangladesh", nativeLabel: "বাংলা — বাংলাদেশ" },
  { value: "bn-IN", label: "Bengali — India", nativeLabel: "বাংলা — ভারত" },
  { value: "bg-BG", label: "Bulgarian — Bulgaria", nativeLabel: "Български" },
  { value: "ca-ES", label: "Catalan — Spain", nativeLabel: "Català" },

  { value: "cmn-Hans-CN", label: "Chinese Mandarin — Simplified, China", nativeLabel: "普通话 — 中国大陆" },
  { value: "cmn-Hans-HK", label: "Chinese Mandarin — Simplified, Hong Kong", nativeLabel: "普通话 — 香港" },
  { value: "cmn-Hant-TW", label: "Chinese Mandarin — Traditional, Taiwan", nativeLabel: "國語 — 台灣" },
  { value: "yue-Hant-HK", label: "Cantonese — Hong Kong", nativeLabel: "廣東話 — 香港" },
  { value: "zh-CN", label: "Chinese — Simplified", nativeLabel: "中文 — 简体" },
  { value: "zh-TW", label: "Chinese — Traditional", nativeLabel: "中文 — 繁體" },

  { value: "hr-HR", label: "Croatian — Croatia", nativeLabel: "Hrvatski" },
  { value: "cs-CZ", label: "Czech — Czech Republic", nativeLabel: "Čeština" },
  { value: "da-DK", label: "Danish — Denmark", nativeLabel: "Dansk" },
  { value: "nl-NL", label: "Dutch — Netherlands", nativeLabel: "Nederlands" },

  { value: "en-AU", label: "English — Australia", nativeLabel: "English — Australia" },
  { value: "en-CA", label: "English — Canada", nativeLabel: "English — Canada" },
  { value: "en-GH", label: "English — Ghana", nativeLabel: "English — Ghana" },
  { value: "en-HK", label: "English — Hong Kong", nativeLabel: "English — Hong Kong" },
  { value: "en-IN", label: "English — India", nativeLabel: "English — India" },
  { value: "en-IE", label: "English — Ireland", nativeLabel: "English — Ireland" },
  { value: "en-KE", label: "English — Kenya", nativeLabel: "English — Kenya" },
  { value: "en-NZ", label: "English — New Zealand", nativeLabel: "English — New Zealand" },
  { value: "en-NG", label: "English — Nigeria", nativeLabel: "English — Nigeria" },
  { value: "en-PH", label: "English — Philippines", nativeLabel: "English — Philippines" },
  { value: "en-SG", label: "English — Singapore", nativeLabel: "English — Singapore" },
  { value: "en-ZA", label: "English — South Africa", nativeLabel: "English — South Africa" },
  { value: "en-TZ", label: "English — Tanzania", nativeLabel: "English — Tanzania" },
  { value: "en-GB", label: "English — United Kingdom", nativeLabel: "English — UK" },
  { value: "en-US", label: "English — United States", nativeLabel: "English — US" },

  { value: "et-EE", label: "Estonian — Estonia", nativeLabel: "Eesti" },
  { value: "fil-PH", label: "Filipino — Philippines", nativeLabel: "Filipino" },
  { value: "fi-FI", label: "Finnish — Finland", nativeLabel: "Suomi" },
  { value: "fr-CA", label: "French — Canada", nativeLabel: "Français — Canada" },
  { value: "fr-FR", label: "French — France", nativeLabel: "Français — France" },
  { value: "gl-ES", label: "Galician — Spain", nativeLabel: "Galego" },
  { value: "ka-GE", label: "Georgian — Georgia", nativeLabel: "ქართული" },
  { value: "de-DE", label: "German — Germany", nativeLabel: "Deutsch" },
  { value: "el-GR", label: "Greek — Greece", nativeLabel: "Ελληνικά" },
  { value: "gu-IN", label: "Gujarati — India", nativeLabel: "ગુજરાતી" },
  { value: "he-IL", label: "Hebrew — Israel", nativeLabel: "עברית" },
  { value: "hi-IN", label: "Hindi — India", nativeLabel: "हिन्दी" },
  { value: "hu-HU", label: "Hungarian — Hungary", nativeLabel: "Magyar" },
  { value: "is-IS", label: "Icelandic — Iceland", nativeLabel: "Íslenska" },
  { value: "id-ID", label: "Indonesian — Indonesia", nativeLabel: "Bahasa Indonesia" },
  { value: "it-IT", label: "Italian — Italy", nativeLabel: "Italiano" },
  { value: "ja-JP", label: "Japanese — Japan", nativeLabel: "日本語" },
  { value: "jv-ID", label: "Javanese — Indonesia", nativeLabel: "Basa Jawa" },
  { value: "kn-IN", label: "Kannada — India", nativeLabel: "ಕನ್ನಡ" },
  { value: "km-KH", label: "Khmer — Cambodia", nativeLabel: "ខ្មែរ" },
  { value: "ko-KR", label: "Korean — South Korea", nativeLabel: "한국어" },
  { value: "lo-LA", label: "Lao — Laos", nativeLabel: "ລາວ" },
  { value: "lv-LV", label: "Latvian — Latvia", nativeLabel: "Latviešu" },
  { value: "lt-LT", label: "Lithuanian — Lithuania", nativeLabel: "Lietuvių" },
  { value: "ms-MY", label: "Malay — Malaysia", nativeLabel: "Bahasa Melayu" },
  { value: "ml-IN", label: "Malayalam — India", nativeLabel: "മലയാളം" },
  { value: "mr-IN", label: "Marathi — India", nativeLabel: "मराठी" },
  { value: "ne-NP", label: "Nepali — Nepal", nativeLabel: "नेपाली" },
  { value: "nb-NO", label: "Norwegian Bokmål — Norway", nativeLabel: "Norsk bokmål" },
  { value: "fa-IR", label: "Persian — Iran", nativeLabel: "فارسی" },
  { value: "pl-PL", label: "Polish — Poland", nativeLabel: "Polski" },
  { value: "pt-BR", label: "Portuguese — Brazil", nativeLabel: "Português — Brasil" },
  { value: "pt-PT", label: "Portuguese — Portugal", nativeLabel: "Português — Portugal" },
  { value: "ro-RO", label: "Romanian — Romania", nativeLabel: "Română" },
  { value: "ru-RU", label: "Russian — Russia", nativeLabel: "Русский" },
  { value: "sr-RS", label: "Serbian — Serbia", nativeLabel: "Српски" },
  { value: "si-LK", label: "Sinhala — Sri Lanka", nativeLabel: "සිංහල" },
  { value: "sk-SK", label: "Slovak — Slovakia", nativeLabel: "Slovenčina" },
  { value: "sl-SI", label: "Slovenian — Slovenia", nativeLabel: "Slovenščina" },

  { value: "es-AR", label: "Spanish — Argentina", nativeLabel: "Español — Argentina" },
  { value: "es-BO", label: "Spanish — Bolivia", nativeLabel: "Español — Bolivia" },
  { value: "es-CL", label: "Spanish — Chile", nativeLabel: "Español — Chile" },
  { value: "es-CO", label: "Spanish — Colombia", nativeLabel: "Español — Colombia" },
  { value: "es-CR", label: "Spanish — Costa Rica", nativeLabel: "Español — Costa Rica" },
  { value: "es-DO", label: "Spanish — Dominican Republic", nativeLabel: "Español — República Dominicana" },
  { value: "es-EC", label: "Spanish — Ecuador", nativeLabel: "Español — Ecuador" },
  { value: "es-SV", label: "Spanish — El Salvador", nativeLabel: "Español — El Salvador" },
  { value: "es-GT", label: "Spanish — Guatemala", nativeLabel: "Español — Guatemala" },
  { value: "es-HN", label: "Spanish — Honduras", nativeLabel: "Español — Honduras" },
  { value: "es-MX", label: "Spanish — Mexico", nativeLabel: "Español — México" },
  { value: "es-NI", label: "Spanish — Nicaragua", nativeLabel: "Español — Nicaragua" },
  { value: "es-PA", label: "Spanish — Panama", nativeLabel: "Español — Panamá" },
  { value: "es-PY", label: "Spanish — Paraguay", nativeLabel: "Español — Paraguay" },
  { value: "es-PE", label: "Spanish — Peru", nativeLabel: "Español — Perú" },
  { value: "es-PR", label: "Spanish — Puerto Rico", nativeLabel: "Español — Puerto Rico" },
  { value: "es-ES", label: "Spanish — Spain", nativeLabel: "Español — España" },
  { value: "es-US", label: "Spanish — United States", nativeLabel: "Español — EE. UU." },
  { value: "es-UY", label: "Spanish — Uruguay", nativeLabel: "Español — Uruguay" },
  { value: "es-VE", label: "Spanish — Venezuela", nativeLabel: "Español — Venezuela" },

  { value: "su-ID", label: "Sundanese — Indonesia", nativeLabel: "Basa Sunda" },
  { value: "sw-KE", label: "Swahili — Kenya", nativeLabel: "Kiswahili — Kenya" },
  { value: "sw-TZ", label: "Swahili — Tanzania", nativeLabel: "Kiswahili — Tanzania" },
  { value: "sv-SE", label: "Swedish — Sweden", nativeLabel: "Svenska" },

  { value: "ta-IN", label: "Tamil — India", nativeLabel: "தமிழ் — இந்தியா" },
  { value: "ta-SG", label: "Tamil — Singapore", nativeLabel: "தமிழ் — சிங்கப்பூர்" },
  { value: "ta-LK", label: "Tamil — Sri Lanka", nativeLabel: "தமிழ் — இலங்கை" },
  { value: "ta-MY", label: "Tamil — Malaysia", nativeLabel: "தமிழ் — மலேசியா" },

  { value: "te-IN", label: "Telugu — India", nativeLabel: "తెలుగు" },
  { value: "th-TH", label: "Thai — Thailand", nativeLabel: "ไทย" },
  { value: "tr-TR", label: "Turkish — Türkiye", nativeLabel: "Türkçe" },
  { value: "uk-UA", label: "Ukrainian — Ukraine", nativeLabel: "Українська" },
  { value: "ur-IN", label: "Urdu — India", nativeLabel: "اردو — بھارت" },
  { value: "ur-PK", label: "Urdu — Pakistan", nativeLabel: "اردو — پاکستان" },
  { value: "vi-VN", label: "Vietnamese — Vietnam", nativeLabel: "Tiếng Việt" },
  { value: "zu-ZA", label: "Zulu — South Africa", nativeLabel: "isiZulu" },

  { value: "custom", label: "Custom BCP 47 language tag", nativeLabel: "Custom" },
];

export const VOICE_LANGUAGE_FALLBACKS = {
  af: "af-ZA",
  am: "am-ET",
  ar: "ar-EG",
  az: "az-AZ",
  bg: "bg-BG",
  bn: "bn-BD",
  ca: "ca-ES",
  cs: "cs-CZ",
  da: "da-DK",
  de: "de-DE",
  el: "el-GR",
  en: "en-US",
  es: "es-ES",
  eu: "eu-ES",
  fa: "fa-IR",
  fi: "fi-FI",
  fil: "fil-PH",
  fr: "fr-FR",
  gl: "gl-ES",
  gu: "gu-IN",
  he: "he-IL",
  hi: "hi-IN",
  hr: "hr-HR",
  hu: "hu-HU",
  hy: "hy-AM",
  id: "id-ID",
  is: "is-IS",
  it: "it-IT",
  ja: "ja-JP",
  jv: "jv-ID",
  ka: "ka-GE",
  km: "km-KH",
  kn: "kn-IN",
  ko: "ko-KR",
  lo: "lo-LA",
  lt: "lt-LT",
  lv: "lv-LV",
  ml: "ml-IN",
  mr: "mr-IN",
  ms: "ms-MY",
  nb: "nb-NO",
  ne: "ne-NP",
  nl: "nl-NL",
  pl: "pl-PL",
  pt: "pt-BR",
  ro: "ro-RO",
  ru: "ru-RU",
  si: "si-LK",
  sk: "sk-SK",
  sl: "sl-SI",
  sq: "sq-AL",
  sr: "sr-RS",
  su: "su-ID",
  sv: "sv-SE",
  sw: "sw-KE",
  ta: "ta-IN",
  te: "te-IN",
  th: "th-TH",
  tr: "tr-TR",
  uk: "uk-UA",
  ur: "ur-PK",
  vi: "vi-VN",
  zh: "cmn-Hans-CN",
  zu: "zu-ZA",
};

export const SUPPORTED_VOICE_LOCALES = new Set(
  VOICE_LANGUAGE_OPTIONS
    .map((item) => item.value)
    .filter((value) => !["auto", "custom"].includes(value)),
);

export function getVoiceLanguageOption(value) {
  return VOICE_LANGUAGE_OPTIONS.find((item) => item.value === value) || null;
}

export function getVoiceLanguageLabel(value) {
  if (!value) return "Browser default";

  if (value === "auto") return "Browser default";

  if (value.startsWith("custom:")) {
    return `Custom — ${value.slice("custom:".length)}`;
  }

  const option = getVoiceLanguageOption(value);
  return option?.label || value;
}
